# Site Info
title: RetroReversing
tagline: 'Retro Reversing'
description: ' Retro Video Game Reverse Engineering.'
baseurl: "/"
url: http://www.retroreversing.com
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty


version: 1.0.0

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Consoles:   
    - '/gameboy/'
    - {Gameboy: '/gameboy/' }
    - {N64: '/n64/' }
#    - { Categories: '/blog/categories/' }
#    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'retro-reversing' # leave blank if you don't want disqus

references: 
  - title: Behind The Screens
    name: BehindTheScreens 
    link: https://www.youtube.com/channel/UC1scN415hiatrUSAg_51xqA
    image: https://yt3.ggpht.com/-59MNhf4K7fw/AAAAAAAAAAI/AAAAAAAAAAA/jA_EjpcyXIg/s288-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: YouTube
    name: youtube 
    link: https://www.youtube.com/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Wayback Machine
    name: wayback 
    link: https://archive.org/web/
    image: /public/references/wayback.jpg
  - title: Devs Play (Double Fine)
    name: DevsPlay 
    link: https://www.youtube.com/user/DoubleFineProd/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Computerphile
    name: computerphile 
    link: https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA
    image: /public/Web-Youtube-alt-2-Metro-icon.png
    
